#import image
FROM node:alpine

#define working directory
WORKDIR '/app'

COPY package.json .

RUN npm install

# Not need beacuse we binding volumes but still here for Dockerfile standalone without the docker-compose.
COPY . .

# Not need beacuse we binding volumes but still here for Dockerfile standalone without the docker-compose.
CMD ["npm","run","start"]